# Generated by Django 6.1 on 2026-08-13 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('ubicacion', models.CharField(max_length=255)),
                ('distancia', models.CharField(max_length=50)),
                ('horario_recogida', models.CharField(max_length=100)),
                ('precio', models.CharField(default='GRATIS', max_length=50)),
                ('categoria', models.CharField(choices=[('Todos', 'Todos'), ('Frutas/Verduras', 'Frutas/Verduras'), ('Pan', 'Pan'), ('Platillos Listos', 'Platillos Listos'), ('Lácteos', 'Lácteos'), ('Carne', 'Carne')], default='Todos', max_length=50)),
                ('imagen_url', models.URLField(blank=True, max_length=500, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
